---
- hosts: web
  become: yes
  gather_facts: true
  tasks:

  - name: copy filebeat.deb
    copy:
      src: /home/ayu/Diplom/filebeat.deb
      dest: /home/user

  - name: install filebeat
    apt:
      deb: /home/user/filebeat.deb

  - name: copy filebeat config file
    copy:
      src: /home/ayu/Diplom/ansible_play/filebeat.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Make sure a service is running
    systemd:
      state: started
      name: filebeat
